services:
  blaze:
    image: "samply/blaze:1.0"
    environment:
      LOG_LEVEL: "debug"
      DB_SEARCH_PARAM_BUNDLE: "/app/custom-search-parameters.json"
    ports:
    - "8080:8080"
    volumes:
    - "./kds/Bundle-mii-exa-meta-searchparam-collection-bundle.json:/app/custom-search-parameters.json:ro"
    - "blaze-data:/app/data"
volumes:
  blaze-data:
